require('../components/header/header.js')();
require('../components/slider/slider.js')();
require('../components/button/button.js')();
require('../components/path/path.js')();
require('../components/contacts/contacts.js')();
require('../components/callback/callback.js')();
require('../components/services-item/services-item.js')();
require('../components/reviews/reviews.js')();
require('../components/to-top/to-top.js')();